### Edit url with database name
### Get all lovebox / connectbox entries

GET http://localhost:9090/lovebox
Accept: application/json


### Get a single lovebox / connectbox entry by ID
GET http://localhost:9090/lovebox/67e5e374d24c064e98201655
Accept: application/json

### Create a new lovebox / connectbox entry
POST http://localhost:9090/lovebox
Content-Type: application/json

{
    "firstName": "Obama",
    "lastName": "Trump",
    "email": "trubama@byupatfhway.com",
    "favoriteHobby": "Politics",
    "birthdayMonth": "July 4",
    "age": "330",
    "city": "Washington DC"
}

### Update an existing lovebox / connectbox entry by ID
PUT http://localhost:9090/lovebox/67e5e50ed24c064e98201659
Content-Type: application/json

{
    "firstName": "Dave",
    "lastName": "William",
    "email": "david@byupathway.edu",
    "favoriteColor": "brown",
    "birthdayMonth": "feb",
    "age": "22",
    "location": "Lagos"
}

### Delete a lovebox / connectbox entry by ID
DELETE http://localhost:9090/connectbox/67e5e50ed24c064e98201659